earnity/earnity/ViewModels/PlaceViewModels/PlaceDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using earnity.Models;
using earnity.Views;

namespace earnity.ViewModels
{
    public class PlaceDetailsViewModel : _BaseViewModel<PlaceDetailsViewModel, Place>
    {
        [Display(Name = "Nazwa restauracji")]
        [Required(ErrorMessage = "Nazwa jest wymagana")]
        public string Name { get; set; }

        [Display(Name = "Opis")]
        [Required(ErrorMessage = "Opis jest wymagany")]
        public string Description { get; set; }

        [Display(Name = "Krótszy opis")]
        [Required(ErrorMessage = "Krótszy opis jest wymagany")]
        public string Description2 { get; set; }

        [Display(Name = "Logo miejsca")]
        [Required(ErrorMessage = "Logo jest wymagane")]
        public string Logo { get; set; }

        [Display(Name = "Kategoria miejsca")]
        public int PlaceCategoryID { get; set; }

        public virtual PlaceCategory PlaceCategory { get; set; }

        [Display(Name = "Geaographical location - Latitude")]
        [Required(ErrorMessage = "Latitude is required")]
        public double Lat { get; set; }

        [Display(Name = "Geaographical location - Longitude")]
        [Required(ErrorMessage = "Longitude is required")]
        public double Lon { get; set; }

        [Display(Name = "Adres")]
        [Required(ErrorMessage = "Adres jest wymagany")]
        public string Address { get; set; }

        [Display(Name = "Godziny otwarcia")]
        [Required(ErrorMessage = "Godziny otwarcia są wymagane")]
        public string WorkingHours { get; set; }

        public override Place ConvertToDbOject()
        {
            var dbObject = new Place
            {
                ID = ID,
                Name = Name,
                Description = Description,
                Description2 = Description2,
                Logo = Logo,
                PlaceCategoryID = PlaceCategoryID,
                PlaceCategory = PlaceCategory,
                Lat = Lat,
                Lon = Lon,
                Address = Address,
                WorkingHours = WorkingHours,
            };

            return dbObject;
        }

        public override PlaceDetailsViewModel ConvertToVM(Place toConvert)
        {
            ID = toConvert.ID;
            Name = toConvert.Name;
            Description = toConvert.Description;
            Description2 = toConvert.Description2;
            Logo = toConvert.Logo;
            PlaceCategoryID = toConvert.PlaceCategoryID;
            PlaceCategory = toConvert.PlaceCategory;
            Lat = toConvert.Lat;
            Lon = toConvert.Lon;
            Address = toConvert.Address;
            WorkingHours = toConvert.WorkingHours;

            return this;
        }
    }
}

earnity/earnity/Controllers/Views/PlaceViewController.cs
using System.Linq;
using earnity.Controllers.API;
using earnity.Factory;
using earnity.Models;
using earnity.Models.Migrations;
using earnity.Other;
using earnity.ViewModels;
using earnity.Views;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace earnity.Controllers.Views
{
    public class PlaceViewController : Controller
    {
        private readonly PlaceFactory _context;

        private readonly PlaceCategoryFactory _categoryContext;

        public PlaceViewController(AppDbContext dbContext)
        {
            _categoryContext =  new PlaceCategoryFactory(dbContext);
            _context = new PlaceFactory(dbContext);
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetPlacesJsonData(int draw, int start, int length)
        {
            string search = Request.Query["search[value]"];
            if (search == null)
            {
                search = "";
            }

            int sortColumn = -1;
            string sortDirection = "asc";

            if (length <=0)
            {
                length = int.MaxValue;
            }

            if (!string.IsNullOrEmpty(Request.Query["order[0][column]"]))
            {
                sortColumn = int.Parse(Request.Query["order[0][column]"]);
            }

            if (!string.IsNullOrEmpty(Request.Query["order[0][dir]"]))
            {
                sortDirection = Request.Query["order[0][column]"];
            }

            var results = _context.Search(search.ToLower());

            if (sortDirection == "asc")
            {
                switch (sortColumn)
                {
                    case 0: results = results.OrderBy(x => x.ID); break;
                    case 1: results = results.OrderBy(x => x.Name); break;
                }
            }
            else
            {
                switch (sortColumn)
                {
                    case 0: results = results.OrderByDescending(x => x.ID); break;
                    case 1: results = results.OrderByDescending(x => x.Name); break;
                }
            }
            int filteredResults = results.Count();

            results = results.Skip(start)
                .Take(length);


            var resultsData = results.ToList()
                .Select(x => new PlaceTableViewModel().ConvertToTableVM(x)).ToList();

            var dataTableData =
                new DataTableData<PlaceTableViewModel>
                {
                    draw = draw,
                    recordsTotal = _context.Count(),
                    totalDisplayRecords = _context.Count(),
                    data = resultsData,
                    recordsFiltered = filteredResults
                };

            return Json(dataTableData);
        }

        [HttpPost]
        public ActionResult PlaceDetails(PlaceDetailsViewModel toAdd)
        {
            Place placeObject;
            if (ModelState.IsValid)
            {
                placeObject = toAdd.ConvertToDbOject();
                if (_context.Get(x=> x.ID == toAdd.ID) != null)
                {
                    _context.Update(placeObject);
                }
                else
                {
                    _context.Add(placeObject);
                }

              
    

                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PlaceDetails(int id)
        {
            ListFiller.Categories(_categoryContext,ViewBag,(int)id);
           

            if (id > 0)
            {
                var placeObject = _context.Get(x => x.ID == id).FirstOrDefault();
                PlaceDetailsViewModel viewModel = new PlaceDetailsViewModel();
                viewModel.ConvertToVM(placeObject);
                return View(viewModel);
            }
            return  View("PlaceDetails");
        }
    }
}

earnity/earnity/Views/PlaceView/Index.cshtml
@using earnity.Factory

@{
    ViewData["Title"] = "Lista Restauracji";
    Layout = "../Shared/_Layout.cshtml";
}

<button class="btn btn-primary" onclick="location.href = '@Url.Action("PlaceDetails","PlaceView")'">Dodaj Restauracje</button>

<div style="padding-top: 20px" class="col-md-12">
    <table id="PlaceList" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nazwa Restauracji</th>
                <th>Opis</th>
                <th>Opis skrócony</th>
                <th>Kategoria</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts {

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="~/app/js/dataTables/searchPlaces.js"></script>
}

earnity/earnity/Views/PlaceView/PlaceDetails.cshtml
@model earnity.ViewModels.PlaceDetailsViewModel

@{
    ViewData["Title"] = "PlaceDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Szczegóły Restauracji</h2>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="PlaceDetails">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description2" class="control-label"></label>
                <input asp-for="Description2" class="form-control" />
                <span asp-validation-for="Description2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
                <div class="form-group">  
                    <label asp-for="PlaceCategoryID" class="control-label"></label>
                    <select asp-for="PlaceCategoryID" class ="form-control" asp-items="ViewBag.Categories"></select>
                </div>

            <div class="form-group">
                <label asp-for="Lat" class="control-label"></label>
                <input asp-for="Lat" class="form-control" />
                <span asp-validation-for="Lat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lon" class="control-label"></label>
                <input asp-for="Lon" class="form-control" />
                <span asp-validation-for="Lon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingHours" class="control-label "></label>
                <input asp-for="WorkingHours" class="form-control"/>
                <span asp-validation-for="WorkingHours" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Powrót do listy</a>
</div>